<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>code.log</string>
        <key>fileTypes</key>
        <array>
            <string>log</string>
        </array>
        <key>name</key>
        <string>Log file</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>match</key>
                <string>\b(?i:((\.)*[a-z]|[0-9])*(Exception|Error|Failure|Fail))\b</string>
                <key>name</key>
                <string>invalid</string>
            </dict>
        </array>
    </dict>
</plist>